const token=window.FLYPPT_TOKEN||'';let connected=false,lastState=null,messageTimer=null;
const $=id=>document.getElementById(id);const commandButtons=[...document.querySelectorAll('[data-command]')];
function url(path){return path+(path.includes('?')?'&':'?')+'token='+encodeURIComponent(token)}
async function api(path,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),4500);try{const response=await fetch(url(path),{cache:'no-store',...options,signal:controller.signal});const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.message||data.error||'操作失败');return data}finally{clearTimeout(timeout)}}
function notify(text,error=false){const el=$('message');el.textContent=text;el.className='message show'+(error?' error':'');clearTimeout(messageTimer);messageTimer=setTimeout(()=>el.className='message',2800)}
function connection(ok){connected=ok;const el=$('connection');el.textContent=ok?'已连接':'已断开';el.className='status '+(ok?'connected':'disconnected');$('syncText').textContent=ok?'最后同步 '+new Date().toLocaleTimeString('zh-CN',{hour12:false}):'连接失败，请检查电脑端服务'}
function timerState(s){return s.timerState||s}
function paint(s){lastState=s;connection(true);const t=timerState(s),p=s.presentationState||{};$('timerText').textContent=t.displayText||'--:--';$('timerStatus').textContent=t.state||'停止';$('timerMode').textContent=t.mode||'倒计时';$('pptName').textContent=p.presentationName||(p.powerPointRunning?'未打开演示文稿':'未检测到 PowerPoint');$('pptPath').textContent=p.presentationPath||'';$('pptPath').title=p.presentationPath||'';$('pptShowState').textContent=p.isSlideShowRunning?'正在放映':'未放映';$('pptSlide').textContent=`${p.currentSlide||0} / ${p.totalSlides||0}`;$('pptScreen').textContent=p.screenMode||'正常';syncOptions(p.presentations||[]);setAvailability(t,p);if(s.message)notify(s.message)}
function syncOptions(items){const select=$('presentationSelect'),old=select.value,signature=items.map(x=>x.id+':'+x.name+':'+x.isActive).join('|');if(select.dataset.signature===signature)return;select.dataset.signature=signature;select.innerHTML='';if(!items.length){select.add(new Option('没有允许的演示文稿',''));return}items.forEach(x=>select.add(new Option((x.isActive?'当前 · ':x.isOpen?'已打开 · ':'')+x.name,x.id)));if(items.some(x=>x.id===old))select.value=old;else{const active=items.find(x=>x.isActive);if(active)select.value=active.id}}
function setAvailability(t,p){const show=!!p.isSlideShowRunning,has=!!p.hasPresentation;commandButtons.forEach(b=>{const cmd=b.dataset.command;b.disabled=!connected||(cmd.startsWith('ppt.')&&((['ppt.previous','ppt.next','ppt.gotoSlide','ppt.endShow','ppt.blackScreenToggle','ppt.whiteScreenToggle'].includes(cmd)&&!show)||(['ppt.startFromBeginning','ppt.startFromCurrent'].includes(cmd)&&!has)))});$('openPresentation').disabled=!connected||!$('presentationSelect').value;$('gotoSlide').disabled=!connected||!show;$('slideNumber').disabled=!connected||!show;$('presentationHint').textContent=p.error||(!p.powerPointInstalled?'本机未安装 Microsoft PowerPoint':!has?'可从文件规则中选择演示文稿':'')}
async function poll(){try{paint(await api('/state'))}catch(e){connection(false);setAvailability({},{});notify('连接失败，请重连：'+e.message,true)}}
async function command(command,extra={}){if(!connected){notify('当前已断开，命令未发送',true);return}try{paint(await api('/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,...extra})}))}catch(e){notify(e.message,true);await poll()}}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab,.page').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.page).classList.add('active')}));
commandButtons.forEach(button=>button.addEventListener('click',()=>command(button.dataset.command)));
$('gotoSlide').addEventListener('click',()=>command('ppt.gotoSlide',{slideNumber:Number($('slideNumber').value)}));
$('openPresentation').addEventListener('click',()=>command('ppt.openPresentation',{presentationId:$('presentationSelect').value}));
poll();setInterval(poll,1000);
